name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@main
        with:
          # Provide the AST portal URL
          base_uri: https://ast.checkmarx.net 
          # Provide the Tenant for AST portal URL
          cx_tenant: cx_cec_na_test_pulse_yang
          # Client ID for AST portal authentication
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          # Secret key for AST portal authentication
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          # Select a Checkmarx Project Name
          project_name: ${{ github.repository }}
          # Branch name
          branch: ${{ github.head_ref || github.ref }}
          # GitHub API Token
          github_token: ${{ github.token }}
          # Additional parameters for AST scan
          additional_params: --report-format sarif --output-path .
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with: 
          # Path to SARIF file relative to the root of the repository
          sarif_file: cx_result.sarif
